- name: Install and Configure Hadoop
  hosts: all
  vars:
    hadoop_home_path: /home/almalinux/hadoop-3.4.0
    private_key_name: cluster_id_rsa
  tasks:
    - name: Downloading Hadoop
      ansible.builtin.get_url:
        url: https://downloads.apache.org/hadoop/common/hadoop-3.4.0/hadoop-3.4.0.tar.gz
        dest: /home/almalinux/hadoop.tar.gz
    - name: Check if Hadoop is already installed
      ansible.builtin.stat:
        path: "{{ hadoop_home_path }}/bin/hadoop"
      register: hadoop_binary
    - name: Unpack Hadoop tgz file
      ansible.builtin.unarchive:
        src: /home/almalinux/hadoop.tar.gz
        dest: /home/almalinux/
        remote_src: true
      register: hadoop_binary_unpack
      when: not hadoop_binary.stat.exists
    - name: Delete the tgz files to save space
      ansible.builtin.file:
        state: absent
        path: /home/almalinux/hadoop.tar.gz
      when: hadoop_binary_unpack is succeeded
    - name: Setup Hadoop environment
      ansible.builtin.blockinfile:
        path: "{{ hadoop_home_path }}/etc/hadoop/hadoop-env.sh"
        block: |
          export JAVA_HOME=/usr/lib/jvm/jre-openjdk
          export HDFS_NAMENODE_USER=almalinux
          export HDFS_DATANODE_USER=almalinux
          export HDFS_SECONDARYNAMENODE_USER=almalinux
          export YARN_RESOURCEMANAGER_USER=almalinux
          export YARN_NODEMANAGER_USER=almalinux
          export HADOOP_HOME={{ hadoop_home_path }}
          export HADOOP_INSTALL=$HADOOP_HOME
          export YARN_HOME=$HADOOP_HOME
          export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
          export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
          export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"
          export HADOOP_SSH_OPTS="-i /home/almalinux/.ssh/{{private_key_name}}"
        state: present

    - name: Setup shell environment
      ansible.builtin.blockinfile:
        path: /home/almalinux/.bashrc
        block: |
          export HADOOP_HOME={{ hadoop_home_path }}
          export JAVA_HOME=/usr/lib/jvm/jre-openjdk
          export PATH=$PATH:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin:$HOME/spark-3.5.3-bin-hadoop3-scala2.13/bin
          export PATH=$PATH:${JAVA_HOME}/bin
          export HADOOP_CONF_DIR=/home/almalinux/hadoop-3.4.0/etc/hadoop
        state: present

    - name: config core-site.xml
      ansible.builtin.blockinfile:
        path: "{{ hadoop_home_path }}/etc/hadoop/core-site.xml"
        insertafter: <configuration>
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        block: |
          <property>
              <name>fs.default.name</name>
              <value>hdfs://mgmtnode:9000/</value>
          </property>
          <property>
            <name>fs.default.FS</name>
            <value>hdfs://mgmtnode:9000/</value>
          </property>
        state: present

    - name: config hdfs-site.xml
      ansible.builtin.blockinfile:
        path: "{{ hadoop_home_path }}/etc/hadoop/hdfs-site.xml"
        insertafter: <configuration>
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        block: |
          <property>
            <name>dfs.namenode.name.dir</name>
              <value>/home/almalinux/hadoop/data/nameNode</value>
          </property>
          <property>
            <name>dfs.datanode.data.dir</name>
            <value>/home/almalinux/hadoop/data/dataNode</value>
          </property>
          <property>
            <name>dfs.namenode.http-address</name>
            <value>mgmtnode:9870</value>
          </property>
          <property>
            <name>dfs.replication</name>
            <value>2</value>
          </property>
          <property>
            <name>dfs.blocksize</name>
            <value>1048576</value>  <!-- 1MB in Bytes -->
          </property>
        state: present

    - name: configure yarn
      ansible.builtin.blockinfile:
        path: "{{ hadoop_home_path }}/etc/hadoop/yarn-site.xml"
        insertafter: <configuration>
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        block: |
          <property>
            <name>yarn.resourcemanager.resource-tracker.address</name>
            <value>mgmtnode:8025</value>
          </property>
          <property>
            <name>yarn.resourcemanager.scheduler.address</name>
            <value>mgmtnode:8035</value>
          </property>
          <property>
            <name>yarn.resourcemanager.address</name>
            <value>mgmtnode:8050</value>
          </property>
          <property>
            <name>yarn.log-aggregation-enable</name>
            <value>true</value>
          </property>
          <property>
            <name>yarn.nodemanager.resource.memory-mb</name>
           <value>28672</value>
          </property>
          <property>
           <name>yarn.scheduler.maximum-allocation-mb</name>
            <value>28672</value>
          </property>
          <property>
            <name>yarn.scheduler.minimum-allocation-mb</name>
            <value>1024</value>
          </property>
          <property>
            <name>yarn.resourcemanager.webapp.address</name>
            <value>mgmtnode:8088</value>
          </property>
          <property>
            <name>yarn.nodemanager.resource.cpu-vcores</name>
          <value>4</value>
          </property>
        state: present

      
