- name: Configure mgmt-node
  hosts: mgmtnode
  vars:
    private_key_name: cluster_id_rsa
    public_key_name: cluster_id_rsa.pub
  tasks:
    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      community.crypto.openssh_keypair:
        path: /home/almalinux/.ssh/{{ private_key_name }}
      register: keypair_result

    - name: Set authorized key for mgmt node
      ansible.posix.authorized_key:
        user: almalinux
        state: present
        key: "{{ keypair_result.public_key }}"
    - name: Copy public key to localmachine to distibute to workernodes 
      ansible.builtin.fetch:
        src: /home/almalinux/.ssh/{{public_key_name}}
        dest: /home/almalinux/.ssh/
        flat: true

