- name: Configure Hadoop
  become: true
  become_user: root
  hosts: all
  tasks:
    - name: Setup Hadoop environment
      ansible.builtin.blockinfile:
        path: /home/almalinux/hadoop-3.4.0/etc/hadoop/hadoop-env.sh
        block: |
          export JAVA_HOME=/usr/lib/jvm/jre-openjdk/
          export HDFS_NAMENODE_USER=almalinux
          export HDFS_DATANODE_USER=almalinux
          export HDFS_SECONDARYNAMENODE_USER=almalinux
          export YARN_RESOURCEMANAGER_USER=almalinux
          export YARN_NODEMANAGER_USER=almalinux
          export HADOOP_HOME=/home/almalinux/hadoop-3.4.0
          export HADOOP_INSTALL=$HADOOP_HOME
          export YARN_HOME=$HADOOP_HOME
          export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
          export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
          export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"
        state: present
    - name: Setup shell environment
      ansible.builtin.blockinfile:
        path: /home/almalinux/.bashrc
        block: |
          export HADOOP_HOME=/home/almalinux/hadoop-3.4.0
          export PATH=${PATH}:${HADOOP_HOME}/bin:${HADOOP_HOME}/sbin:$HOME/spark-3.5.3-bin-hadoop3-scala2.13/bin
        

