- name: Set Worker Node Hostname
  hosts: workernodes
  become: true
  become_user: root
  tasks: 
  - name: Set hostname
    ansible.builtin.hostname:
      name: workernode{{lookup('ansible.utils.index_of', groups["workernodes"], 'eq', inventory_hostname) + 1 }}
      use: systemd
  - name: Ensure hostname persists after reboot
    ansible.builtin.copy:
      content: "workernode{{lookup('ansible.utils.index_of', groups['workernodes'], 'eq', inventory_hostname) + 1 }}"
      dest: /etc/hostname