- name: Configure mgmt-node
  hosts: mgmtnode
  tasks:
    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      community.crypto.openssh_keypair:
        path: /home/almalinux/.ssh/crypt_id_rsa

    - name: Set authorized key for mgmt node
      ansible.posix.authorized_key:
        user: almalinux
        state: present
        key: "{{ lookup('file', '/home/almalinux/.ssh/crypt_id_rsa.pub') }}"

    - name: Copy the public key to the control machine
      local_action:
        module: copy
        content: "{{ lookup('file', '/home/almalinux/.ssh/crypt_id_rsa.pub') }}"
        dest: "{{ lookup('env', 'HOME') }}/.ssh/crypt_id_rsa.pub"
      run_once: true

