- name: Run agggregation script on Merizo Search Engine
  hosts: "{{ groups['workernodes'][1] }}"
  tasks:
    - name: Create HDFS output directory for aggregated results
      ansible.builtin.shell: hdfs dfs -mkdir -p /summaryOutputs
    - name: Run aggregation script for Ecoli Models
      ansible.builtin.shell: spark-submit /home/almalinux/merizo-search/aggregate_parsed_results.py ecoli
      register: aggregation_results
    - name: Run aggregation script for Human Models
      ansible.builtin.shell: spark-submit /home/almalinux/merizo-search/aggregate_parsed_results.py human
      register: aggregation_results