- name: Upload analysis results to minio
  hosts: "{{ groups['workernodes'][0] }}"
  tasks:
    - name: Copy upload-analysis-results.py to node for uploading analysis results
      ansible.builtin.copy:
        src: /home/almalinux/eda-coursework/upload-analysis-results.py
        dest: /home/almalinux/upload-analysis-results.py
        mode: '0755'
        remote_src: false
    - name: Copy minio password file to node for uploading analysis results
      ansible.builtin.copy:
        src: /home/almalinux/eda-coursework/.miniopass
        dest: /home/almalinux/.miniopass
        remote_src: false
    - name: Upload analysis results to minio for parsed/ecoli
      ansible.builtin.shell: python upload-analysis-results.py parsed/ecoli
    - name: Upload analysis results to minio for data/ecoli
      ansible.builtin.shell: python upload-analysis-results.py data/ecoli
    # - name: Upload analysis results to minio for parsed/human
    #   ansible.builtin.shell: python upload-analysis-results.py parsed/human
    # - name: Upload analysis results to minio for data/human
    #   ansible.builtin.shell: python upload-analysis-results.py data/human
    - name: Upload analysis results to minio for Summary Outputs
      ansible.builtin.shell: python upload-analysis-results.py summaryOutputs