- name: Installing Critical Python Dependencies For Analysis
  hosts: workernodes
  become: true
  become_user: root
  tasks:
  - name: Installing Python3 dependencies
    ansible.builtin.pip:
      name:
        - numpy
        - pandas
        - biopython
        - "torch --index-url https://download.pytorch.org/whl/cpu"
        - scipy
        - faiss-cpu
        - rotary_embedding_torch
        - natsort
        - matplotlib
        - pyspark
        - python-dotenv
        - minio
      state: latest
  - name: Clean pip cache
    ansible.builtin.shell: pip cache purge
  
