- name: Download and distribute AlphaFold DB models into HDFS
  hosts: "{{ groups['workernodes'][0] }}"
  tasks:
    - name: Ensure AlphaFold directory exists
      ansible.builtin.file:
        path: /home/almalinux/alphafold-db/
        state: directory
    - name: Create local directory for AlphaFold DB Human model
      ansible.builtin.file:
        path: /home/almalinux/alphafold-db/UP000005640_9606_HUMAN_v4
        state: directory
    - name: Download AlphaFold DB Human model
      ansible.builtin.get_url:
        url: https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000005640_9606_HUMAN_v4.tar
        dest: /home/almalinux/alphafold-db/
    - name: Create local directory for AlphaFold DB Human model
      ansible.builtin.file:
        path: /home/almalinux/alphafold-db/UP000005640_9606_HUMAN_v4
        state: directory
    - name: Unpack AlphaFold DB Human model
      ansible.builtin.unarchive:
        src: /home/almalinux/alphafold-db/UP000005640_9606_HUMAN_v4.tar
        dest: /home/almalinux/alphafold-db/UP000005640_9606_HUMAN_v4
        remote_src: true
    - name: Delete AlphaFold Human zipped model
      ansible.builtin.file:
        state: absent
        path: /home/almalinux/alphafold-db/UP000005640_9606_HUMAN_v4.tar
    - name: Delete all CIF files to create disk space
      ansible.builtin.shell: "rm -f /home/almalinux/alphafold-db/UP000005640_9606_HUMAN_v4*.cif.gz"
    - name: Unzip remaining PDB files
      ansible.builtin.shell: "gunzip /home/almalinux/alphafold-db/UP000005640_9606_HUMAN_v4/*.gz"
    - name: Create HDFS directory for AlphaFold DB Human Models
      ansible.builtin.shell: hdfs dfs -mkdir -p /alphafold/human
    - name: Run script to distribute AlphaFold Human models into HDFS
      ansible.builtin.shell: python /home/almalinux/merizo-search/distribute_data.py /home/almalinux/alphafold-db/UP000005640_9606_HUMAN_v4/ /alphafold/human/
      register: hdfs_human_upload
    - name: Delete AlphaFold Human models from local storage
      ansible.builtin.file:
        state: absent
        path: /home/almalinux/alphafold-db/UP000005640_9606_HUMAN_v4
