- name: Download and distribute AlphaFold DB models into HDFS
  hosts: "{{ groups['workernodes'] | random }}"
  tasks:
    - name: Ensure AlphaFold directory exists
      ansible.builtin.file:
        path: /home/almalinux/alpahfold-db/
        state: directory
    - name: Create HDFS directory for AlphaFold DB Ecoli models
      ansible.builtin.shell: hdfs dfs -mkdir -p /alphafold/ecoli
    - name: Create local directory for AlphaFold DB Ecoli model
      ansible.builtin.file:
        path: /home/almalinux/alpahfold-db/UP000000625_83333_ECOLI_v4
        state: directory
    - name: Download AlphaFold DB E. coli model
      ansible.builtin.get_url:
        url: https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000000625_83333_ECOLI_v4.tar
        dest: /home/almalinux/alpahfold-db/
    - name: Unpack AlphaFold DB E. coli model
      ansible.builtin.unarchive:
        src: /home/almalinux/alpahfold-db/UP000000625_83333_ECOLI_v4.tar
        dest: /home/almalinux/alpahfold-db/UP000000625_83333_ECOLI_v4
        remote_src: true
    - name: Find all gzipped PDB files
      find:
        paths: /home/almalinux/alpahfold-db/UP000000625_83333_ECOLI_v4
        patterns: "*.pdb.gz"
      register: pdb_files
    - name: Unzip PDB files (suppressed logs)
      ansible.builtin.shell: gunzip {{ item.path }}
      with_items: "{{ pdb_files.files }}"
      no_log: true
    - name: Run script to distribute AlphaFold EColi models into HDFS
      ansible.builtin.shell: python /merizo-search/distribute_data.py /home/almalinux/alpahfold-db/UP000000625_83333_ECOLI_v4/ /alphafold/ecoli/
      register: hdfs_ecoli_upload
    - name: Delete AlphaFold Ecoli models from local storage
      ansible.builtin.file:
        state: absent
        path: /home/almalinux/alpahfold-db/
      when: hdfs_ecoli_upload is succeeded