---
- name: Install and Configure Grafana
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Install Grafana
      dnf:
        name: grafana
        state: present
        update_cache: yes

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Check Grafana service status
      systemd:
        name: grafana-server
      register: grafana_status