- name: Download and distribute AlphaFold DB models into HDFS
  hosts: mgmtnode
  tasks:
    - name: Ensure AlphaFold directory exists
      ansible.builtin.file:
        path: /home/almalinux/alpahfold-db/
        state: directory
    - name: Download AlphaFold DB Human model
      ansible.builtin.get_url:
        url: https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000005640_9606_HUMAN_v4.tar
        dest: /home/almalinux/alpahfold-db/
    - name: Download AlphaFold DB E. coli model
      ansible.builtin.get_url:
        url: https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000000625_83333_ECOLI_v4.tar
        dest: /home/almalinux/alpahfold-db/
    - name: Creae directory for AlphaFold DB Human model
      ansible.builtin.file:
        path: /home/almalinux/alpahfold-db/UP000005640_9606_HUMAN_v4
        state: directory
    - name: Creae directory for AlphaFold DB Ecoli model
      ansible.builtin.file:
        path: /home/almalinux/alpahfold-db/UP000000625_83333_ECOLI_v4
        state: directory
    - name: Unpack AlphaFold DB Human model
      ansible.builtin.unarchive:
        src: /home/almalinux/alpahfold-db/UP000005640_9606_HUMAN_v4.tar
        dest: /home/almalinux/alpahfold-db/UP000005640_9606_HUMAN_v4
        remote_src: true
    - name: Unpack AlphaFold DB E. coli model
      ansible.builtin.unarchive:
        src: /home/almalinux/alpahfold-db/UP000000625_83333_ECOLI_v4.tar
        dest: /home/almalinux/alpahfold-db/UP000000625_83333_ECOLI_v4
        remote_src: true