---
- name: Install Prometheus and Node Exporter
  hosts: mgmtnode
  become: true
  become_user: root
  gather_facts: true 

  tasks:
    - name: Install golang
      dnf:
        name: golang
        state: present

    - name: Install EPEL repository
      dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present
        disable_gpg_check: true

    - name: Import EPEL GPG key
      rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9
        state: present

    - name: Install Prometheus and Node Exporter packages
      dnf:
        name: 
          - golang-github-prometheus
          - golang-github-prometheus-node-exporter
        state: present
        disable_gpg_check: true

    - name: Ensure Prometheus config directory exists
      file:
        path: /etc/prometheus
        state: directory
        mode: '0755'

    - name: Start Prometheus
      ansible.builtin.shell: prometheus --config.file=/etc/prometheus/prometheus.yml
      become: true
      become_user: root
      async: 0
      poll: 0 