- name: Install Merizo Search Code
  hosts: all
  tasks:
    - name: Distribute Merizo search code
      ansible.builtin.copy:
        src: /home/almalinux/eda-coursework/merizo-search
        dest: /home/almalinux/merizo-search
        remote_src: false