---
- name: format HDFS and start Hadoop services
  hosts: mgmtnode
  tasks:
    - name: Check if HDFS is already formatted
      ansible.builtin.stat:
        path: /home/almalinux/hadoop-3.4.0/dfs/name
      register: hdfs_stat

    - name: Format HDFS if not formatted
      ansible.builtin.shell: hdfs namenode -format
      when: not hdfs_stat.stat.exists

    - name: format cluster
      ansible.builtin.shell: hdfs namenode -format
 
    - name: start dfs
      ansible.builtin.shell: nohup /home/almalinux/hadoop-3.4.0/sbin/start-dfs.sh
      environment:
        HADOOP_SSH_OPTS: "-o StrictHostKeyChecking=no"
    
    - name: start yarn
      ansible.builtin.shell: nohup /home/almalinux/hadoop-3.4.0/sbin/start-yarn.sh
      environment:
        HADOOP_SSH_OPTS: "-o StrictHostKeyChecking=no"