- name: Installing Required Tools
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: Installing Quality of Life Tools
    ansible.builtin.dnf:
      name:
        - vim
        - emacs
        - nano
        - tmux
        - net-tools
        - bind-utils
        - htop
        - git
        - ansible
        - make
        - unzip
        - wget
        - links
      state: latest
  - name: Installing Python3
    ansible.builtin.dnf:
      name:
        - python3
        - python3-pip
      state: latest
  - name: Installing Java
    ansible.builtin.dnf:
     name: java-11-openjdk
     state: latest  
  - name: Downloading Hadoop
    ansible.builtin.get_url:
      url: https://downloads.apache.org/hadoop/common/hadoop-3.4.0/hadoop-3.4.0.tar.gz
      dest: /home/almalinux/hadoop.tar.gz
  - name: Unpack Hadoop tgz file
    ansible.builtin.unarchive:
      src: /home/almalinux/hadoop.tar.gz
      dest: /home/almalinux/
      remote_src: true

